export const ROLEPOST_REQUEST = 'src/Role/ROLEPOST_REQUEST';
export const ROLEPOST_SUCCESS = 'src/Role/ROLEPOST_SUCCESS';
export const ROLEPOST_FAILURE = 'src/Role/ROLEPOST_FAILURE';

export const ROLEUPDATE_REQUEST = 'src/Role/ROLEUPDATE_REQUEST';
export const ROLEUPDATE_SUCCESS = 'src/Role/ROLEUPDATE_SUCCESS';
export const ROLEUPDATE_FAILURE = 'src/Role/ROLEUPDATE_FAILURE';

export const ROLEDELETE_REQUEST = 'src/Role/ROLEDELETE_REQUEST';
export const ROLEDELETE_SUCCESS = 'src/Role/ROLEDELETE_SUCCESS';
export const ROLEDELETE_FAILURE = 'src/Role/ROLEDELETE_FAILURE';

export const FETCH_POST = 'src/Role/FETCH_POST';